- hosts: all
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Set power state for nodes managed by OpenStack
      when: bm_management == "openstack"
      block:
        - name: Get power state
          delegate_to: localhost
          ansible.builtin.command: >-
            openstack baremetal node show {{ node_name }} -f value -c power_state
          register: power_state

        - name: Power off node
          delegate_to: localhost
          when: >-
            power_state.stdout != "power off"
          ansible.builtin.command: >-
            openstack baremetal node power off {{ node_name }}

        - name: Wait for power off
          delegate_to: localhost
          ansible.builtin.command: >-
            openstack baremetal node show {{ node_name }} -f value -c power_state
          register: power_state
          until: >-
            power_state.stdout == "power off"
          retries: 12
          delay: 10

    - name: Set power state for nodes through the BMC
      when: bm_management == "bmc" and bmc_type == "idrac"
      block:
        - name: Get power state
          delegate_to: "{{ bmc_addr }}"
          ansible.builtin.raw: racadm serveraction powerstatus
          register: power_state

        - name: Power off node
          delegate_to: "{{ bmc_addr }}"
          when: >-
            "off" not in power_state.stdout|lower
          ansible.builtin.raw: racadm serveraction powerdown

        - name: Wait for power off
          delegate_to: "{{ bmc_addr }}"
          ansible.builtin.raw: racadm serveraction powerstatus
          register: power_state
          until: >-
            "off" in power_state.stdout|lower
          retries: 12
          delay: 10

    - name: Configure virtual media (idrac)
      when: >
        bmc_type == "idrac"
      delegate_to: "{{ bmc_addr }}"
      ansible.builtin.raw: "{{ item }}"
      register: result
      failed_when: >-
        "error" in result.stdout|lower
      loop:
        - racadm remoteimage -d
        - racadm remoteimage -c -l "{{ boot_image_url }}"
        - racadm set idrac.serverboot.FirstBootDevice VCD-DVD
        - racadm set idrac.serverboot.BootOnce 1

    - name: Configure virtual media (lenovo)
      when: bmc_type == "lenovo"
      block:
        - name: Mount boot image
          delegate_to: "{{ bmc_addr }}"
          ansible.builtin.raw: "{{ item }}"
          register: result
          failed_when: >-
            "[cli]err" in result.stdout|lower
          loop:
            - rdmount -umount
            - rdmount -map -t http -ro -l "{{ boot_image_url }}"
            - rdmount -mount

        - name: Request one-time boot from virtual media
          delegate_to: localhost
          ansible.builtin.command: >-
            ipmitool -I lanplus -H {{ bmc_addr }}
            -U {{ bmc_user }} -P {{ bmc_password }}
            chassis bootdev cdrom

    - name: Power on node through OpenStack
      when: bm_management == "openstack"
      delegate_to: localhost
      ansible.builtin.command: >-
        openstack baremetal node power on {{ node_name }}

    - name: Power on node through the BMC
      when: bm_management == "bmc" and bmc_type == "idrac"
      delegate_to: "{{ bmc_addr }}"
      ansible.builtin.raw: racadm serveraction powerup
