- hosts: all
  gather_facts: false
  tasks:
    - name: Get power state
      delegate_to: localhost
      ansible.builtin.command: >-
        openstack baremetal node show {{ node_name }} -f value -c power_state
      register: power_state

    - name: Power off node
      delegate_to: localhost
      when: >-
        power_state.stdout != "power off"
      ansible.builtin.command: >-
        openstack baremetal node power off {{ node_name }}

    - name: Wait for power off
      delegate_to: localhost
      ansible.builtin.command: >-
        openstack baremetal node show {{ node_name }} -f value -c power_state
      register: power_state
      until: >-
        power_state.stdout == "power off"
      retries: 12
      delay: 10

    - name: Configure idrac
      when: >
        bmc_type == "idrac"
      delegate_to: "{{ bmc_addr }}"
      ansible.builtin.raw: "{{ item }}"
      register: result
      failed_when: >-
        "error" in result.stdout|lower
      loop:
        - racadm remoteimage -d
        - racadm remoteimage -c -l "{{ boot_image_url }}"
        - racadm set idrac.serverboot.FirstBootDevice VCD-DVD
        - racadm set idrac.serverboot.BootOnce 1

    - name: Configure lenovo
      when: >
        bmc_type == "lenovo"
      delegate_to: "{{ bmc_addr }}"
      ansible.builtin.raw: "{{ item }}"
      register: result
      failed_when: >-
        "[cli]err" in result.stdout|lower
      loop:
        - rdmount -umount
        - rdmount -map -t http -ro -l "{{ boot_image_url }}"
        - rdmount -mount

    - name: Request one-time boot from virtual media
      when: >
        bmc_type == "lenovo"
      delegate_to: localhost
      ansible.builtin.uri:
        url: "https://{{ bmc_addr }}/redfish/v1/Systems/1"
        method: PATCH
        url_username: "{{ bmc_user }}"
        url_password: "{{ bmc_password }}"
        force_basic_auth: true
        validate_certs: false
        headers:
          Content-Type: application/json
        body_format: json
        body:
          Boot:
            BootSourceOverrideTarget: Cd
            BootSourceOverrideEnabled: Once

    - name: Power on node
      delegate_to: localhost
      ansible.builtin.command: >-
        openstack baremetal node power on {{ node_name }}
