- hosts: localhost
  gather_facts: false
  tasks:
    - name: Test kubernetes connectivity
      ansible.builtin.command: oc -n {{ inventory_namespace }} get infraenv {{ inventory_name }}

- hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Get network interfaces from host
      ansible.builtin.command: openstack esi node network list --node {{ node_name }} -f json
      register: node_network_out

    - name: Get list of agents
      ansible.builtin.command: oc -n {{ inventory_namespace }} get agent -o json
      register: agents_out

    - name: Select MAC Address
      ansible.builtin.set_fact:
        mac_address: "{{ (node_network_out.stdout|from_json)[0]['MAC Address'] }}"

    - ansible.builtin.debug:
        msg: "Looking for agent matching {{ mac_address }}"

    - name: Find matching agent
      ansible.builtin.set_fact:
        matched_agent: >-
          {{ (agents_out.stdout|from_json) | json_query("items[?contains(status.inventory.interfaces[*].macAddress, '%s')]" % mac_address) }}
      vars:
        mac_address: "{{ (node_network_out.stdout|from_json)[0]['MAC Address'] }}"

    - ansible.builtin.debug:
        msg: "{{ matched_agent[0].metadata.name }}"
      when: matched_agent|length>0

    - name: Update agent hostname
      when: matched_agent|length>0
      ansible.builtin.command: >-
        oc -n {{ inventory_namespace }} patch agent {{ agent_name }}
          --type merge
          --patch '{"spec": {"hostname": "{{node_name|lower}}" } }'
      vars:
        agent_name: "{{ matched_agent[0].metadata.name }}"
