- hosts: localhost
  gather_facts: false
  tasks:
    - name: Test kubernetes connectivity
      ansible.builtin.command: oc -n {{ inventory_namespace }} get infraenv {{ inventory_name }}

- hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Get MAC address (OpenStack)
      when: bm_management == "openstack"
      block:
        - name: Get host metadata
          ansible.builtin.command: openstack baremetal node show -f json {{ node_name }}
          register: node_out

        - name: Get network interfaces from host
          ansible.builtin.command: openstack esi node network list --node {{ node_name }} -f json
          register: node_network_out

        - name: Select MAC Address
          ansible.builtin.set_fact:
            mac_addr: "{{ (node_network_out.stdout|from_json)[0]['MAC Address'] }}"

    - ansible.builtin.debug:
        msg: "Looking for agent matching {{ mac_addr }}"

    - name: Get list of agents
      ansible.builtin.command: oc -n {{ inventory_namespace }} get agent -o json
      register: agents_out

    - name: Find matching agent
      ansible.builtin.set_fact:
        matched_agent: >-
          {{ (agents_out.stdout|from_json) | json_query("items[?contains(status.inventory.interfaces[*].macAddress, '%s')]" % mac_addr) }}
   
    - ansible.builtin.debug:
        msg: "{{ matched_agent[0].metadata.name }}"
      when: matched_agent|length>0

    - name: Update agent hostname
      when: matched_agent|length>0
      ansible.builtin.command: >-
        oc -n {{ inventory_namespace }} patch agent {{ agent_name }}
          --type merge
          --patch '{"spec": {"hostname": "{{node_name|lower}}" } }'
      vars:
        agent_name: "{{ matched_agent[0].metadata.name }}"

    - name: Label agent (OpenStack)
      when: matched_agent|length>0 and bm_management == "openstack"
      ansible.builtin.command: >-
        oc -n {{ inventory_namespace }} label agent {{ agent_name }} --overwrite
          openstack/resource-class={{ node.resource_class}}
          openstack/uuid={{ node.uuid }}
          massopen.cloud/cluster={{ cluster }}
      vars:
        agent_name: "{{ matched_agent[0].metadata.name }}"
        node: "{{ node_out.stdout|from_json }}"

    - name: Label agent (non-OpenStack)
      when: matched_agent|length>0 and bm_management != "openstack"
      ansible.builtin.command: >-
        oc -n {{ inventory_namespace }} label agent {{ agent_name }} --overwrite
          openstack/resource-class={{ resource_class}}
          massopen.cloud/cluster={{ cluster }}
      vars:
        agent_name: "{{ matched_agent[0].metadata.name }}"
        node: "{{ node_out.stdout|from_json }}"

    - name: Approve agent
      when: matched_agent|length>0
      ansible.builtin.command: >-
        oc -n {{ inventory_namespace }} patch agent {{ agent_name }}
          --patch '{"spec": {"approved": true}}' --type merge
      vars:
        agent_name: "{{ matched_agent[0].metadata.name }}"
